### ISSUE TITLE
Suggestion on how to improve documentation

### ISSUE THREAD

**Issue by rafaelrinaldi** [LemonBoy/autobahn#1]
It would be way better if you added a screen shot/recording of the plugin in action. Otherwise it's hard to "buy" it (as in understand why the hell you would even bother to download it).

Just a suggestion.

**Comment by LemonBoy** [comment]
I'd be really happy if someone adjusted the README to be nicer, I'm not that great with words :)

**Comment by LemonBoy** [comment]
Done! Is it any better ?

**Comment by rafaelrinaldi** [comment]
@LemonBoy Yes, it is! :ok_hand:
